### ISSUE TITLE
can has python3.8 please

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/xarray-fits#37]
```
(test) oms@herbie:~/Downloads$ python -c "import xarrayfits"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/oms/.venv/test/lib/python3.8/site-packages/xarrayfits/__init__.py", line 30, in <module>
    from xarrayfits.fits import xds_from_fits
  File "/home/oms/.venv/test/lib/python3.8/site-packages/xarrayfits/fits.py", line 5, in <module>
    from future_builtins import zip, map
ModuleNotFoundError: No module named 'future_builtins'
```

Working on 3.10, but would be nice to have 3.8 still.

**Comment by sjperkins** [comment]
Most of `xarray-fits`' upstream packages have deprecated support for python 3.8, which is already EOL.

- https://github.com/ratt-ru/dask-ms/pull/306#issuecomment-1898079125
